export const hotels = [
  {
    id: "hotel-1",
    name: "Grand Plaza",
    location: "New York",
    rating: 4.5,
    description: "Modern hotel in the heart of the city",
    image: "/big-up/big-up-app-bg.webp",
  },
  {
    id: "hotel-2",
    name: "Ocean View Resort",
    location: "Miami",
    rating: 4.7,
    description: "Beachfront resort with stunning ocean views",
    image: "/big-up/big-up-app-bg.webp",
  },
  {
    id: "hotel-3",
    name: "Mountain Retreat",
    location: "Denver",
    rating: 4.2,
    description: "Cozy lodge near the mountains",
    image: "/big-up/big-up-app-bg.webp",
  },
  {
    id: "hotel-4",
    name: "City Lights Inn",
    location: "Chicago",
    rating: 4.0,
    description: "Boutique hotel near downtown attractions",
    image: "/big-up/big-up-app-bg.webp",
  },
  {
    id: "hotel-5",
    name: "Desert Oasis",
    location: "Phoenix",
    rating: 4.3,
    description: "Relaxing stay in the desert",
    image: "/big-up/big-up-app-bg.webp",
  },
];
